### ISSUE TITLE
Multiple videos on a single page

### ISSUE THREAD

**Issue by thribiere** [sanderheilbron/vimeo.ga.js#40]
Is it possible to track more than one vimeo video on a single page ?

I tried to add my events : 
ga('send' ...) under each video, but if i read only the first one, i get many events into analytics.

I would associate events with a specific iframe ? Is it possible ?

Thks

**Comment by sanderheilbron** [comment]
Yes!

Please see documentation:
https://github.com/sanderheilbron/vimeo.ga.js/blob/master/readme.md#basic

**Comment by chercka** [comment]
But since events are not reset, the first video played will fire this event and the second video played will not - right?

I am experiencing this on a page with multiple videos. I can fire events to play, pause, resume, etc but once it's fired on a video, it cannot fire on another. Is this expected, or should it fire an event pr video just by having a unique iframe and video player id?
